In [2]:
import pandas as pd
import urllib.request

from bs4 import BeautifulSoup

In [3]:
# scrape players injured by cummulative season 2018

source = urllib.request.urlopen('https://www.spotrac.com/nhl/injured-reserve/2018/').read()
soup = BeautifulSoup(source, "html.parser")
table = soup.find_all('table', attrs={'class':'datatable'})

In [4]:
c=0
for tb in table:
#     print(tb)
    c=c+1
print(c)

5

In [5]:
first_table=table[4]
table_rows = first_table.find_all('tr')

res = []
for tr in table_rows:
    td = tr.find_all('td')
    row = [tr.text.strip() for tr in td if tr.text.strip()]
    if row:
        res.append(row)
injNHLdf_18 = pd.DataFrame(res)
# print(df.count)

#print(df)

In [6]:
injNHLdf_18 = pd.DataFrame(res, columns=["PLAYER", "POS", "TEAM", "REASONS", "WEEKS", "2018 CAP", "2018 CASH"])

injNHLdf_18.head()

              PLAYER POS TEAM          REASONS WEEKS     2018 CAP    2018 CASH
0     Filip Forsberg   C  NSH             Hand    38  $17,339,818  $17,339,818
1        Jack Eichel   C  BUF       Upper Body   170   $9,139,710   $9,139,710
2      Martin Hanzal   C  DAL  Upper Body/Back   245   $6,256,810   $6,586,090
3  Henrik Zetterberg  LW  DET             Back   186   $6,083,316   $6,083,316
4        Marc Methot   D  DAL       Lower Body   222   $5,848,368   $5,848,368

In [28]:
# scrape players injured by cummulative season 2017
source = urllib.request.urlopen('https://www.spotrac.com/nhl/injured-reserve/2017/').read()
soup = BeautifulSoup(source, "html.parser")
table = soup.find_all('table', attrs={'class':'datatable'})
first_table=table[4]
table_rows = first_table.find_all('tr')

res = []
for tr in table_rows:
    td = tr.find_all('td')
    row = [tr.text.strip() for tr in td if tr.text.strip()]
    if row:
        res.append(row)
injNHLdf_17 = pd.DataFrame(res)
# print(df.count)
injNHLdf_17 = pd.DataFrame(res, columns=["PLAYER", "POS", "TEAM", "REASONS", "WEEKS", "2017 CAP", "2017 CASH"])

injNHLdf_17.head()

,PLAYER,POS,TEAM,REASONS,WEEKS,2017 CAP,2017 CASH
0,Zach Bogosian,D,BUF,Leg/Lower Body/Ribs,"1,440","$40,618,191","$42,229,787"
1,Kris Letang,D,PIT,Lower Body/Upper Body,876,"$35,275,728","$35,275,728"
2,Ryan Callahan,RW,TBL,Upper Body/Lower Body,915,"$29,467,545","$33,024,090"
3,Semyon Varlamov,G,COL,Lower Body/Groin,909,"$29,774,042","$30,251,317"
4,Mikhail Grabovski,C,VGK,Concussion,630,"$16,935,660","$20,322,540"

In [29]:
# df2 = injNHLdf_17.groupby(['PLAYER'])['REASONS'].count().to_frame('Injury Count').reset_index()


# countdf_17 = injNHLdf_17.groupby(["PLAYER", "REASONS"]).size().reset_index(name='count')
# countdf_17.head()
# Avg_asthma_byState = pd.DataFrame(asthma_melted_df.groupby("State")["Asthma Mortality"].mean())
countdf = pd.DataFrame(injNHLdf_17.groupby('PLAYER')['REASONS'].count().reset_index())
countdf.head()

           PLAYER  REASONS
0  Adam Cracknell        1
1    Adam Larsson        1
2      Adam Lowry        1
3    Adam McQuaid        1
4      Al Montoya        1

In [31]:
#write into csv file
injNHLdf_17.to_csv('injNHL_17.csv', index=True, header=True)
injNHLdf_18.to_csv('injNHL_18.csv', index=True, header=True)