In [13]:
import pandas as pd
import urllib.request

from bs4 import BeautifulSoup

In [14]:
# scrape players Time on Ice 2018

source = urllib.request.urlopen('http://www.espn.com/nhl/statistics/player/_/stat/timeonice/sort/avgTimeOnIce/year/2018').read()
soup = BeautifulSoup(source, "html.parser")
table = soup.find_all('table', attrs={'class':'tablehead'})

In [15]:
c=0
for tb in table:
#     print(tb)
    c=c+1
print(c)

1

In [16]:
first_table=table[0]

table_rows = first_table.find_all('tr')

res = []
for tr in table_rows:
    td = tr.find_all('td')
    row = [tr.text.strip() for tr in td if tr.text.strip()]
    if row:
        res.append(row)
timeNHL_df_18 = pd.DataFrame(res)

# print(df_1819.count)

In [17]:
timeNHL_df_18 = pd.DataFrame(res, columns=["RK","PLAYER", "TEAM", "GP", "G", "A", "PTS", "+/-", "TOI/G", "SHFT", "SHFT/G", "PROD"])
timeNHL_df_18.head()

,RK,PLAYER,TEAM,GP,G,A,PTS,+/-,TOI/G,SHFT,SHFT/G,PROD
0,RK,PLAYER,TEAM,GP,G,A,PTS,+/-,TOI/G,SHFT,SHFT/G,PROD
1,1,"Drew Doughty, D",LA,82,10,50,60,23,26:50,2511,30.6,36:40
2,2,"Ryan Suter, D",MIN,78,6,45,51,-1,26:47,2108,27.0,40:57
3,3,"Erik Karlsson, D",OTT,71,9,53,62,-25,26:44,2161,30.4,30:37
4,4,"Rasmus Ristolainen, D",BUF,73,6,35,41,-25,26:30,2115,29.0,47:10

In [18]:
timeNHL_df_18 = timeNHL_df_18.iloc[1:]
timeNHL_df_18.head()

,RK,PLAYER,TEAM,GP,G,A,PTS,+/-,TOI/G,SHFT,SHFT/G,PROD
1,1,"Drew Doughty, D",LA,82,10,50,60,23,26:50,2511,30.6,36:40
2,2,"Ryan Suter, D",MIN,78,6,45,51,-1,26:47,2108,27.0,40:57
3,3,"Erik Karlsson, D",OTT,71,9,53,62,-25,26:44,2161,30.4,30:37
4,4,"Rasmus Ristolainen, D",BUF,73,6,35,41,-25,26:30,2115,29.0,47:10
5,5,"Victor Hedman, D",TB,77,17,46,63,32,25:51,2117,27.5,31:35

In [19]:
timeNHL_df_18 = timeNHL_df_18.drop_duplicates(subset='PLAYER', keep='first', inplace=False)
timeNHL_df_18 = timeNHL_df_18.drop('RK', axis=1)

timeNHL_df_18.head()

                  PLAYER TEAM  GP   G   A PTS  +/-  TOI/G  SHFT SHFT/G   PROD
1        Drew Doughty, D   LA  82  10  50  60   23  26:50  2511   30.6  36:40
2          Ryan Suter, D  MIN  78   6  45  51   -1  26:47  2108   27.0  40:57
3       Erik Karlsson, D  OTT  71   9  53  62  -25  26:44  2161   30.4  30:37
4  Rasmus Ristolainen, D  BUF  73   6  35  41  -25  26:30  2115   29.0  47:10
5       Victor Hedman, D   TB  77  17  46  63   32  25:51  2117   27.5  31:35

In [20]:
timeNHL_df_18 = timeNHL_df_18.drop(timeNHL_df_18.index[10])

timeNHL_df_18[['PLAYER','POS']] = timeNHL_df_18['PLAYER'].str.split(',',expand=True)

timeNHL_df_18.head()

               PLAYER TEAM  GP   G   A PTS  +/-  TOI/G  SHFT SHFT/G   PROD POS
1        Drew Doughty   LA  82  10  50  60   23  26:50  2511   30.6  36:40   D
2          Ryan Suter  MIN  78   6  45  51   -1  26:47  2108   27.0  40:57   D
3       Erik Karlsson  OTT  71   9  53  62  -25  26:44  2161   30.4  30:37   D
4  Rasmus Ristolainen  BUF  73   6  35  41  -25  26:30  2115   29.0  47:10   D
5       Victor Hedman   TB  77  17  46  63   32  25:51  2117   27.5  31:35   D

In [21]:
# flip first last name to last first
timeNHL_df_18["PLAYER"] = [" ".join(n.split(" ")[::-1]) for n in timeNHL_df_18["PLAYER"]]
timeNHL_df_18.head()

               PLAYER TEAM  GP   G   A PTS  +/-  TOI/G  SHFT SHFT/G   PROD POS
1        Doughty Drew   LA  82  10  50  60   23  26:50  2511   30.6  36:40   D
2          Suter Ryan  MIN  78   6  45  51   -1  26:47  2108   27.0  40:57   D
3       Karlsson Erik  OTT  71   9  53  62  -25  26:44  2161   30.4  30:37   D
4  Ristolainen Rasmus  BUF  73   6  35  41  -25  26:30  2115   29.0  47:10   D
5       Hedman Victor   TB  77  17  46  63   32  25:51  2117   27.5  31:35   D

In [22]:
# scrape players Time on Ice 2017

source = urllib.request.urlopen('http://www.espn.com/nhl/statistics/player/_/stat/timeonice/sort/avgTimeOnIce/year/2017').read()
soup = BeautifulSoup(source, "html.parser")
table = soup.find_all('table', attrs={'class':'tablehead'})


c=0
for tb in table:
#     print(tb)
    c=c+1
print(c)

first_table=table[0]

table_rows = first_table.find_all('tr')

res = []
for tr in table_rows:
    td = tr.find_all('td')
    row = [tr.text.strip() for tr in td if tr.text.strip()]
    if row:
        res.append(row)
timeNHL_df_17 = pd.DataFrame(res)

# print(df_1819.count)

1

In [23]:
timeNHL_df_17 = pd.DataFrame(res, columns=["RK","PLAYER", "TEAM", "GP", "G", "A", "PTS", "+/-", "TOI/G", "SHFT", "SHFT/G", "PROD"])
timeNHL_df_17.head()

,RK,PLAYER,TEAM,GP,G,A,PTS,+/-,TOI/G,SHFT,SHFT/G,PROD
0,RK,PLAYER,TEAM,GP,G,A,PTS,+/-,TOI/G,SHFT,SHFT/G,PROD
1,1,"Dustin Byfuglien, D",WPG,80,13,39,52,10,27:27,2327,29.1,42:13
2,2,"Drew Doughty, D",LA,82,12,32,44,8,27:09,2657,32.4,50:35
3,3,"Ryan Suter, D",MIN,82,9,31,40,34,26:55,2319,28.3,55:11
4,4,"Erik Karlsson, D",OTT,77,17,54,71,10,26:50,2425,31.5,29:06

In [24]:
timeNHL_df_17 = timeNHL_df_17.drop_duplicates(subset='PLAYER', keep='first', inplace=False)
timeNHL_df_17 = timeNHL_df_17.drop('RK', axis=1)

timeNHL_df_17.head()

                PLAYER  TEAM  GP   G   A  PTS  +/-  TOI/G  SHFT  SHFT/G   PROD
0               PLAYER  TEAM  GP   G   A  PTS  +/-  TOI/G  SHFT  SHFT/G   PROD
1  Dustin Byfuglien, D   WPG  80  13  39   52   10  27:27  2327    29.1  42:13
2      Drew Doughty, D    LA  82  12  32   44    8  27:09  2657    32.4  50:35
3        Ryan Suter, D   MIN  82   9  31   40   34  26:55  2319    28.3  55:11
4     Erik Karlsson, D   OTT  77  17  54   71   10  26:50  2425    31.5  29:06

In [25]:
timeNHL_df_17 = timeNHL_df_17.iloc[1:]
timeNHL_df_17.head()

                  PLAYER TEAM  GP   G   A PTS +/-  TOI/G  SHFT SHFT/G   PROD
1    Dustin Byfuglien, D  WPG  80  13  39  52  10  27:27  2327   29.1  42:13
2        Drew Doughty, D   LA  82  12  32  44   8  27:09  2657   32.4  50:35
3          Ryan Suter, D  MIN  82   9  31  40  34  26:55  2319   28.3  55:11
4       Erik Karlsson, D  OTT  77  17  54  71  10  26:50  2425   31.5  29:06
5  Rasmus Ristolainen, D  BUF  79   6  39  45  -9  26:28  2341   29.6  46:28

In [26]:
timeNHL_df_17[['PLAYER','POS']] = timeNHL_df_17['PLAYER'].str.split(',',expand=True)
timeNHL_df_17.head()

               PLAYER TEAM  GP   G   A PTS +/-  TOI/G  SHFT SHFT/G   PROD POS
1    Dustin Byfuglien  WPG  80  13  39  52  10  27:27  2327   29.1  42:13   D
2        Drew Doughty   LA  82  12  32  44   8  27:09  2657   32.4  50:35   D
3          Ryan Suter  MIN  82   9  31  40  34  26:55  2319   28.3  55:11   D
4       Erik Karlsson  OTT  77  17  54  71  10  26:50  2425   31.5  29:06   D
5  Rasmus Ristolainen  BUF  79   6  39  45  -9  26:28  2341   29.6  46:28   D

In [29]:
# flip first last name to last first
timeNHL_df_17["PLAYER"] = [" ".join(n.split(" ")[::-1]) for n in timeNHL_df_17["PLAYER"]]
timeNHL_df_17.head()

               PLAYER TEAM  GP   G   A PTS +/-  TOI/G  SHFT SHFT/G   PROD POS
1    Dustin Byfuglien  WPG  80  13  39  52  10  27:27  2327   29.1  42:13   D
2        Drew Doughty   LA  82  12  32  44   8  27:09  2657   32.4  50:35   D
3          Ryan Suter  MIN  82   9  31  40  34  26:55  2319   28.3  55:11   D
4       Erik Karlsson  OTT  77  17  54  71  10  26:50  2425   31.5  29:06   D
5  Rasmus Ristolainen  BUF  79   6  39  45  -9  26:28  2341   29.6  46:28   D

In [28]:
#write into csv file
timeNHL_df_17.to_csv('NHLTimeonIce_17.csv', index=True, header=True)
timeNHL_df_18.to_csv('NHLTimeonIce_18.csv', index=True, header=True)